package com.ixeken.drafto.domain.model

/**
 * Catalogo completo de los 112 emojis vectoriales SVG incluidos en Drafto Brain OS.
 */
object DraftoEmojiAssets {
    val list: List<String> = listOf(
        "Angry face with horns.svg",
        "Angry face.svg",
        "Anguished face.svg",
        "Anxious face with sweat.svg",
        "Astonished face.svg",
        "Beaming face with smiling eyes.svg",
        "Clown face.svg",
        "Cold face.svg",
        "Confounded face.svg",
        "Confused face.svg",
        "Cowboy hat face.svg",
        "Crying face.svg",
        "Disappointed face.svg",
        "Disguised face.svg",
        "Dizzy face.svg",
        "Dotted line face.svg",
        "Downcase face with sweat.svg",
        "Drooling face.svg",
        "Exploding head.svg",
        "Expressionless face.svg",
        "Face blowing a kiss.svg",
        "Face exhaling.svg",
        "Face holding back tears.svg",
        "Face in clouds.svg",
        "Face savoring food.svg",
        "Face screaming in fear.svg",
        "Face vomiting.svg",
        "Face with diagonal mouth.svg",
        "Face with hand over mouth.svg",
        "Face with head bandage.svg",
        "Face with medical mask.svg",
        "Face with monocle.svg",
        "Face with open eyes and hand over mouth.svg",
        "Face with open mouth.svg",
        "Face with peeking eye.svg",
        "Face with raised eyebrow.svg",
        "Face with rolling eyes.svg",
        "Face with spiral eyes.svg",
        "Face with steam from nose.svg",
        "Face with symbols on mouth.svg",
        "Face with tears of joy.svg",
        "Face with thermometer.svg",
        "Face with tongue.svg",
        "Face without mouth.svg",
        "Fearful face.svg",
        "Flushed face.svg",
        "Frowning face with open mouth.svg",
        "Frowning face.svg",
        "Grimacing face.svg",
        "Grinning face with big eyes.svg",
        "Grinning face with smiling eyes.svg",
        "Grinning face with sweat.svg",
        "Grinning face.svg",
        "Grinning squinting face.svg",
        "Head shaking horizontally.svg",
        "Head shaking vertically.svg",
        "Hot face.svg",
        "Hugging face.svg",
        "Hushed face.svg",
        "Kissing face with closed eyes.svg",
        "Kissing face with smiling eyes.svg",
        "Kissing face.svg",
        "Loudly crying face.svg",
        "Lying face.svg",
        "Melting face.svg",
        "Mewing face.svg",
        "Money mouth face.svg",
        "Nauseated face.svg",
        "Nerd face.svg",
        "Neutral face.svg",
        "Partying face.svg",
        "Pensive face.svg",
        "Persevering face.svg",
        "Pile of poo.svg",
        "Pleading face.svg",
        "Pouting face.svg",
        "Relieved face.svg",
        "Robot.svg",
        "Rolling on the floor laughing.svg",
        "Sad but relieved face.svg",
        "Saluting face.svg",
        "Shaking face.svg",
        "Shushing face.svg",
        "Skull.svg",
        "Sleeping face.svg",
        "Sleepy face.svg",
        "Slightly frowning face.svg",
        "Slightly smiling face.svg",
        "Smiling face with halo.svg",
        "Smiling face with heart-eyes.svg",
        "Smiling face with hearts.svg",
        "Smiling face with horns.svg",
        "Smiling face with smiling eyes.svg",
        "Smiling face with sunglasses.svg",
        "Smiling face with tear.svg",
        "Smiling face.svg",
        "Smirking face.svg",
        "Sneezing face.svg",
        "Squinting face with tongue.svg",
        "Star-struck.svg",
        "Thinking face.svg",
        "Tired face.svg",
        "Unamused face.svg",
        "Upside-down face.svg",
        "Weary face.svg",
        "Winking face with tongue.svg",
        "Winking face.svg",
        "Woozy face.svg",
        "Worried face.svg",
        "Yawning face.svg",
        "Zany face.svg",
        "Zipper-mouth face.svg"
    )

    fun getAssetUri(fileName: String): String = "file:///android_asset/emojis/$fileName"
}
